version: '3.7'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi-app:latest
    command: uvicorn main:app --host 0.0.0.0 --port=8000
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.app-http.rule=Host(`testfastapi.rahulmistri.eu.org`)
      - traefik.http.routers.app-http.tls=true
      - traefik.http.routers.app-http.tls.certresolver=letsencrypt

    deploy:
      mode: replicated
      replicas: 3
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.apiservice_web.rule=PathPrefix(`/`)"
    #   - "traefik.http.services.apiservice_web.loadbalancer.server.port=80"
    # network_mode: host
    # ports:
    #   - 8000:8000
    # env_file:
    #   - .env

  traefik:
    image: traefik
    # command: 
    #     - "--api.insecure=true"
    #     - "--providers.docker=true"
    #     - "--providers.docker.exposedbydefault=false"
    #     - "--entrypoints.web.address=:80"
    ports:
      - 80:80
      - 443:443
      - 8080:8080 # Traefik dashboard, if needed
    restart: always
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD/traefik/traefik.toml:/etc/traefik/traefik.toml
      - traefik-public-certificates:/certificates

volumes:
  traefik-public-certificates:
